[project]
name = "qmad_history"
description = "document every step in optimizing qcd_ml_accel_dirac "
requires-python=">=3.4"
dependencies=['torch >= 2.4.0, <2.5']
version = "0.0.1"

[build-system]
requires = ["torch", "setuptools", "ninja", "wheel"]
build-backend = "setuptools.build_meta"
